version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    ports:
      - "5000:5000"
  app2:
    build: ./flask-jinja-tutorial/flask_jinja_tutorial
    container_name: "Flask_App_2"
    ports:
      - "5001:5001"
  app3:
    build: ./flask-wtforms-tutorial/flask_wtforms_tutorial
    container_name: "Flask_App_3"
    ports:
      - "5002:5002"